### ISSUE TITLE
首页调试报错

### ISSUE THREAD

**Issue by atange** [pd4d10/cnode-weapp#1]
WAService.js:9 Uncaught Error: module "bower_components/timeago.js/dist/timeago.js" is not definedrequire @ WAService.js:9(anonymous function) @ WAService.js:9(anonymous function) @ utils.js [sm]:1require @ WAService.js:9(anonymous function) @ WAService.js:9(anonymous function) @ app.js [sm]:1require @ WAService.js:9(anonymous function) @ app.js [sm]:8
WAService.js:9 Uncaught Error: module "bower_components/zanui-weapp/dist/tab/index.js" is not definedrequire @ WAService.js:9(anonymous function) @ WAService.js:9(anonymous function) @ index.js [sm]:1require @ WAService.js:9(anonymous function) @ index.js [sm]:10
appservice:16 Sun Aug 13 2017 07:38:10 GMT+0800 (中国标准时间) page 编译错误
appservice:17  pages/index/index 出现脚本错误或者未正确调用 Page()(anonymous function) @ appservice:17
WAService.js:9 Uncaught Error: module "bower_components/wxParse/wxParse/wxParse.js" is not definedrequire @ WAService.js:9(anonymous function) @ WAService.js:9(anonymous function) @ detail.js [sm]:1require @ WAService.js:9(anonymous function) @ detail.js [sm]:10
appservice:22 Sun Aug 13 2017 07:38:10 GMT+0800 (中国标准时间) page 编译错误
appservice:23  pages/detail/detail 出现脚本错误或者未正确调用 Page()(anonymous function) @ appservice:23
WAService.js:9 Uncaught Error: module "bower_components/timeago.js/dist/timeago.js" is not definedrequire @ WAService.js:9(anonymous function) @ WAService.js:9(anonymous function) @ utils.js [sm]:1require @ WAService.js:9(anonymous function) @ WAService.js:9(anonymous function) @ message.js [sm]:1require @ WAService.js:9(anonymous function) @ message.js [sm]:3
appservice:28 Sun Aug 13 2017 07:38:10 GMT+0800 (中国标准时间) page 编译错误
appservice:29  pages/message/message 出现脚本错误或者未正确调用 Page()(anonymous function) @ appservice:29
WAService.js:9 Uncaught Error: module "bower_components/zanui-weapp/dist/switch/index.js" is not definedrequire @ WAService.js:9(anonymous function) @ WAService.js:9(anonymous function) @ me.js [sm]:1require @ WAService.js:9(anonymous function) @ me.js [sm]:4
appservice:34 Sun Aug 13 2017 07:38:10 GMT+0800 (中国标准时间) page 编译错误
WAService.js:9 Uncaught Error: module "bower_components/timeago.js/dist/timeago.js" is not definedrequire @ WAService.js:9(anonymous function) @ WAService.js:9(anonymous function) @ utils.js [sm]:1require @ WAService.js:9(anonymous function) @ WAService.js:9(anonymous function) @ star.js [sm]:1require @ WAService.js:9(anonymous function) @ star.js [sm]:3
appservice:58 Sun Aug 13 2017 07:38:10 GMT+0800 (中国标准时间) page 编译错误
appservice:59  pages/star/star 出现脚本错误或者未正确调用 Page()(anonymous function) @ appservice:59
VM123:1 Sun Aug 13 2017 07:38:13 GMT+0800 (中国标准时间) wxss 文件，编译错误
VM123:2 /app.wxss
Error: ENOENT: no such file or directory, open 'E:\cnode-weapp-master\bower_components\zanui-weapp\dist\index.wxss'(anonymous function) @ VM123:2
WAService.js:3 thirdScriptError
Cannot read property 'globalData' of undefined;at "pages/index/index" page lifeCycleMethod onLoad function
TypeError: Cannot read property 'globalData' of undefined
    at e.onLoad (http://690505116.appservice.open.weixin.qq.com/pages/recent-topics/recent-topics.js:8:18)
    at e.<anonymous> (http://690505116.appservice.open.weixin.qq.com/WAService.js:8:31793)
    at C (http://690505116.appservice.open.weixin.qq.com/WAService.js:8:20005)
    at E (http://690505116.appservice.open.weixin.qq.com/WAService.js:8:21579)
    at j (http://690505116.appservice.open.weixin.qq.com/WAService.js:8:21845)
    at .<anonymous> (http://690505116.appservice.open.weixin.qq.com/WAService.js:8:23728)
    at http://690505116.appservice.open.weixin.qq.com/WAService.js:8:28571
    at http://690505116.appservice.open.weixin.qq.com/WAService.js:4:9968
    at Array.forEach (native)
    at .<anonymous> (http://690505116.appservice.open.weixin.qq.com/WAService.js:4:9948)errorReport @ WAService.js:3thirdErrorReport @ WAService.js:3(anonymous function) @ WAService.js:3(anonymous function) @ WAService.js:8C @ WAService.js:8E @ WAService.js:8j @ WAService.js:8(anonymous function) @ WAService.js:8(anonymous function) @ WAService.js:8(anonymous function) @ WAService.js:4(anonymous function) @ WAService.js:4(anonymous function) @ WAService.js:4(anonymous function) @ asdebug.js:1n.emit @ asdebug.js:1r @ asdebug.js:1(anonymous function) @ asdebug.js:1g @ asdebug.js:1(anonymous function) @ asdebug.js:1
VM125:1 Sun Aug 13 2017 07:38:14 GMT+0800 (中国标准时间) WXML Runtime warning
VM125:2 ./pages/index/index.wxml
VM125:3  Path "/bower_components/zanui-weapp/dist/tab/index.wxml" not found from "./pages/index/index.wxml".
> 1 | <import src="/bower_components/zanui-weapp/dist/tab/index.wxml" />
    | ^
  2 | <import src="/bower_components/zanui-weapp/dist/loadmore/index.wxml" />
  3 | <import src="/templates/topic.wxml" />
  4 | 
VM126:1 Sun Aug 13 2017 07:38:14 GMT+0800 (中国标准时间) WXML Runtime warning
VM126:2 ./pages/index/index.wxml
VM126:3  Path "/bower_components/zanui-weapp/dist/loadmore/index.wxml" not found from "./pages/index/index.wxml".
  1 | <import src="/bower_components/zanui-weapp/dist/tab/index.wxml" />
> 2 | <import src="/bower_components/zanui-weapp/dist/loadmore/index.wxml" />
    |  ^
  3 | <import src="/templates/topic.wxml" />
  4 | 
  5 | <view class="container">
VM127:1 Sun Aug 13 2017 07:38:14 GMT+0800 (中国标准时间) WXML Runtime warning
VM127:2 ./pages/index/index.wxml
VM127:3  Template "zan-tab" not found.
   5 | <view class="container">
   6 |   <view class="tab">
>  7 |     <template is="zan-tab" data="{{tab: tab, componentId: 'tab'}}"></template>
     |                  ^
   8 |   </view>
   9 |   <view>
  10 |     <view wx:for="{{topics}}" wx:key="id">
VM128:1 Sun Aug 13 2017 07:38:14 GMT+0800 (中国标准时间) WXML Runtime warning
VM128:2 ./pages/index/index.wxml
VM128:3  Template "zan-loadmore" not found.
  11 |       <template is="topic" data="{{topic: item}}" />
  12 |     </view>
> 13 |     <template is="zan-loadmore" data="{{loading: true}}" />
     |                  ^
  14 |   </view>
  15 | </view>
  16 |

**Comment by pd4d10** [comment]
@sonong Try `bower install`

**Comment by meidawei** [comment]
为什么我在PC端总是报错，可以帮忙解答一下吗

**Comment by meidawei** [comment]
VM350:2 ./bower_components/wxParse/app.wxss
File not found: /wxParse/wxParse.wxss
(anonymous) @ VM350:2

**Comment by meidawei** [comment]
我想问问一定要填写你自己的appid才可以查看吗？还有就是我bower install后，在最新版的微信开发者工具打开总是有问题，可否加一下微信聊聊怎么解决
